#!/usr/bin/env bash

#------------------------------------------------------------------------------
# ----------- https://github.com/jmooring/bash-function-library.git -----------
#
# Test suite for password functions
#
# @author  Joe Mooring
#
# @file
# Performs assertion password functions testing system in this library.
#
# This simple testing mechanism has no provision for the construction and
# deconstruction of unit test scaffolding.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# @function
# Declares assertions.
#
# @return global array $assertions
#   This is a one dimensional array. Each element is a pipe delimited list
#   of three values in this sequence:
#
#   1. Function to test (example: bfl::join)
#   2. Parameters to pass to function (example, "1" "2" "3")
#   3. Expected return code (example: 0)
#------------------------------------------------------------------------------
declare_assertions() {
  declare -ga assertions=(
#   bfl::generate_password
    'bfl::generate_password||1'
    'bfl::generate_password|"" ""|1'
    'bfl::generate_password|""|1'
    'bfl::generate_password|" "|1'
    'bfl::generate_password|"a"|1'
    'bfl::generate_password|"1.1"|1'
    'bfl::generate_password|"-1"|1'
    'bfl::generate_password|"7"|1'
    'bfl::generate_password|"8"|0'
  )
}