#!/usr/bin/env bash

set +u    # подключаем внешнюю "библиотеку"
[[ ${_GUARD_BFL_AUTOLOAD} -eq 1 ]] || { . /etc/getConsts || exit 1; . "${BASH_FUNCTIONS_LIBRARY}"; }
#------------------------------------------------------------------------------
# @file
# Creates documentation for library functions.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# @function
#   Displays usage message.
#
# @return String $msg
#   The usage message.
#------------------------------------------------------------------------------
usage() {
  local msg
  msg=$(cat << EOT
Creates documentation for library functions.

Usage:    ${0##*/}    # $(basename "$0")

Example:  ${0##*/}    # $(basename "$0")
EOT
  )
  printf "%s\\n" "${msg}"
  }

#------------------------------------------------------------------------------
# @function
#   Main function.
#
# shellcheck disable=1090
#------------------------------------------------------------------------------
main() {
  # Verify argument count.
  [[ $# -eq 0 ]] || { usage; return 1; }

  # Verify dependencies.
  [[ ${_BFL_HAS_GREP} -eq 1 ]] || { bfl::error "dependency 'grep' not found"; return ${BFL_ErrCode_Not_verified_dependency}; }
  [[ ${_BFL_HAS_SED} -eq 1 ]]  || { bfl::error "dependency 'sed' not found";  return ${BFL_ErrCode_Not_verified_dependency}; }

  # Declare readonly variables (sorted by name).
  local -r btx3="\\x60\\x60\\x60"   # 3 backticks
  local -r header="# Bash Function Library\\n\\n## Function List"
  local -r output_file_name="function-list.md"

  # Declare all other variables (sorted by name).
  local {body,footer,func_examples,func_name,func_params,func_returns,func_summary,header_examples,header_params,header_returns,toc}=
  local -i iErr

  # Create footer.
  footer="*Last updated: $(date --iso-8601=s).*"

  local file   # Loop through the files.
  # "$(dirname "${BASH_FUNCTIONS_LIBRARY}")"
  for file in "${BASH_FUNCTIONS_LIBRARY%/*}"/*/_*.sh; do
      # Set the headers for each section. Need to do this each time through the
      # loop because one or more may be pluralized if there is more than one.
      header_examples="Example"
      header_params="Parameter"
      header_returns="Return"

      # Find the function name (one line).
      func_name=$(grep -Eo -m1 "bfl::.+" "${file}" | sed 's/().*//') ||
        { iErr=$?; bfl::error "Unable to find function name"; return ${iErr}; }

      # Find the function description (one entry).
      func_summary=$(grep -A1 "@function" "${file}" | tail -n1 | sed 's/^# *//') ||
        { iErr=$?; bfl::error "Unable to find function description."; return ${iErr}; }

      # The sed command to format @param and @return entries:
      #
      #   1. Remove leading "#" and spaces from each line.
      #   2. Add ">" to the beginning of each line.
      #   3. Replace ">@tag " with a newline.

      # Find the function parameters (zero or more entries).
      set +e
      func_params=$(grep -A1 --no-group-separator "# *@param" "${file}" | sed 's/^# *// ; s/^/>/ ; s/>@param /\\n/')
      [[ "$(grep -c "# *@param" "${file}")" -gt "1" ]] && header_params+="s"
      set -e

      # Find the function returns (zero or more entries).
      set +e
      func_returns=$(grep -A1 --no-group-separator "# *@return" "${file}" | sed 's/^# *// ; s/^/>/ ; s/>@return /\\n/')
      [[ "$(grep -c "# *@return" "${file}")" -gt "1" ]] && header_returns+="s"
      set -e

      # The sed command to format @example entries:
      #
      #   1. Delete the line containing the @example tag.
      #   2. Remove leading "#" and spaces from each line.

      # Find the function examples (zero or more entries).
      set +e
      func_examples=$(grep -A1 --no-group-separator "# *@example" "${file}" | sed '/.*@example.*/d ; s/^# *//' )
      [[ "$(grep -c "# *@example" "${file}")" -gt "1" ]] && header_examples+="s"
      set -e

      # Surround the examples with 3 backticks.
      func_examples="\\n${btx3}bash\\n${func_examples}\\n${btx3}\\n"

      # Add to the table of contents.
      toc+="* [${func_name}](#${func_name//::/})\\n"

      # Add to the body.
      body+="## ${func_name}\\n\\n"
      body+="${func_summary}\\n\\n"
      bfl::is_empty "${func_params}"   || body+="**${header_params}**\\n"
      bfl::is_empty "${func_params}"   || body+="${func_params}\\n\\n"
      bfl::is_empty "${func_returns}"  || body+="**${header_returns}**\\n"
      bfl::is_empty "${func_returns}"  || body+="${func_returns}\\n\\n"
      bfl::is_empty "${func_examples}" || body+="**${header_examples}**\\n"
      bfl::is_empty "${func_examples}" || body+="${func_examples}\\n"
  done

  printf  "%b\\n\\n%b\\n%b---\\n%b\\n" "${header}" "${toc}" "${body}" "${footer}" \
    > "${BASH_FUNCTIONS_LIBRARY%/*}"/docs/"${output_file_name}"

  }

set -euo pipefail
main "$@"
